[pytest]
addopts = --instafail --tb=short --color=auto
log_level = DEBUG
log_cli = True
norecursedirs =
    vendor
    nimbledeps
    *.egg-info
log_file = log/test.log
log_cli_format = %(asctime)s.%(msecs)03d %(levelname)s [%(name)s] %(message)s
log_file_format = %(asctime)s.%(msecs)03d %(levelname)s [%(name)s] %(message)s
timeout = 300
markers =
    smoke: marks tests as smoke test (deselect with '-m "not smoke"')
    docker_required: test requires Docker nodes (WakuNode)
    waku_test_fleet: marks tests that run against a live Waku test fleet
    store2000: marks tests that use 2000 store messages
