name: RLN Tests Common

on:
  workflow_call:
    inputs:
      node1:
        required: true
        description: "Node that usually publishes messages. Used for all tests"
        type: string
        default: "wakuorg/nwaku:latest"
      node2:
        required: true
        description: "Node that usually queries for published messages. Used for all tests"
        type: string
        default: "wakuorg/nwaku:latest"
      additional_nodes:
        required: false
        description: "Additional optional nodes used in e2e tests, separated by ,"
        type: string
        default: "wakuorg/nwaku:latest,wakuorg/nwaku:latest,wakuorg/nwaku:latest"
      caller:
        required: false
        description: "Workflow caller. Used in reporting"
        type: string

env:
  FORCE_COLOR: "1"
  NODE_1: ${{ inputs.node1 }}
  NODE_2: ${{ inputs.node2 }}
  ADDITIONAL_NODES: ${{ inputs.additional_nodes }}
  CALLER: ${{ inputs.caller || 'manual' }}
  RLN_CREDENTIALS: ${{ secrets.RLN_CREDENTIALS }}

jobs:

  tests:
    name: tests
    strategy:
      fail-fast: false
      matrix:
        shard: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
  # total number of shards =18 means tests will split into 18 thread and run in parallel to increase execution speed
  # command for sharding :
  # pytest --shard-id=<shard_number> --num-shards=<total_shards>
  # shard 16 for test_rln.py file as they shall run sequentially
  # shard 17 for test_cursor_many_msgs.py as it takes time >7 mins
    runs-on: ubuntu-latest
    timeout-minutes: 120
    outputs:
      jobResult_0: ${{ steps.set_result.outputs.JOB_RESULT_0 }}
      jobResult_1: ${{ steps.set_result.outputs.JOB_RESULT_1 }}
      jobResult_2: ${{ steps.set_result.outputs.JOB_RESULT_2 }}
      jobResult_3: ${{ steps.set_result.outputs.JOB_RESULT_3 }}
      jobResult_4: ${{ steps.set_result.outputs.JOB_RESULT_4 }}
      jobResult_5: ${{ steps.set_result.outputs.JOB_RESULT_5 }}
      jobResult_6: ${{ steps.set_result.outputs.JOB_RESULT_6 }}
      jobResult_7: ${{ steps.set_result.outputs.JOB_RESULT_7 }}
      jobResult_8: ${{ steps.set_result.outputs.JOB_RESULT_8 }}
      jobResult_9: ${{ steps.set_result.outputs.JOB_RESULT_9 }}
      jobResult_10: ${{ steps.set_result.outputs.JOB_RESULT_10 }}
      jobResult_11: ${{ steps.set_result.outputs.JOB_RESULT_11 }}
      jobResult_12: ${{ steps.set_result.outputs.JOB_RESULT_12 }}
      jobResult_13: ${{ steps.set_result.outputs.JOB_RESULT_13 }}
      jobResult_14: ${{ steps.set_result.outputs.JOB_RESULT_14 }}
      jobResult_15: ${{ steps.set_result.outputs.JOB_RESULT_15 }}
      jobResult_16: ${{ steps.set_result.outputs.JOB_RESULT_16 }}
      jobResult_17: ${{ steps.set_result.outputs.JOB_RESULT_17 }}
    steps:

    - uses: actions/checkout@v4

    - name: Remove unwanted software
      uses: ./.github/actions/prune-vm

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install system deps for tc / nsenter
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          util-linux \
          iproute2 \
          sudo \
          ca-certificates \
          curl

    - run: pip install -r requirements.txt

    - name: Run tests

      run: |
        if [ "${{ matrix.shard }}" == "16" ]; then
            pytest tests/relay/test_rln.py 
        fi
